[package]
name = "rusty-skr"
version = "0.1.0"
edition = "2021"

[dependencies]
stm32g0 = { version = "^0.15", features = ["stm32g081", "rt"] }
stm32g0xx-hal = { version = "^0.1", features = ["stm32g081", "rt"] }
panic-halt = "^0.2"
cortex-m = "^0.7"
cortex-m-rt = "^0.6"
